# Site
title:              An Nguyen
bio:               'I am a PhD student in the <a href="http://cogsci.jhu.edu/" style="color:blue">Cognitive Science department</a> at Johns Hopkins University. My research interests include psycholinguistics, bilingualism, and simulation models. I am currently working with <a href="http://cogsci.jhu.edu/directory/geraldine-legendre" style="color:blue">Geraldine Legendre</a> on the topic of language acquisition.'
description:        ""
reading_time:       true
words_per_minute:   200
logo:               'assets/img/profile.jpg'
background:         'assets/img/101.jpg'
tiled_bg:           true   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://annguyen0212.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              anguye60@jhu.edu
#twitter:            username
#facebook:           username
github-url:         https://github.com/annguyen0212
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
soundcloud:        https://soundcloud.com/fishpig2511
#weibo:             username
#flickr:            username
#rcodepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
